import Foundation

final class ConfigStore {
    private let fileURL: URL

    init() {
        let appSupport = FileManager.default.urls(for: .applicationSupportDirectory, in: .userDomainMask)[0]
        let dir = appSupport.appendingPathComponent("Darter", isDirectory: true)
        try? FileManager.default.createDirectory(at: dir, withIntermediateDirectories: true)
        fileURL = dir.appendingPathComponent("config.json")
        Self.migrateFromPreviousName(into: dir, configFile: fileURL)
    }

    /// The app was renamed from AndrewKeys to Darter, which moved this
    /// directory. Carry a pre-rename config across once so existing users
    /// keep their bindings, preset slots and settings instead of silently
    /// getting defaults. Copies rather than moves, so the old install keeps
    /// working if someone runs both.
    private static func migrateFromPreviousName(into dir: URL, configFile: URL) {
        let fm = FileManager.default
        guard !fm.fileExists(atPath: configFile.path) else { return }

        let legacyDir = dir.deletingLastPathComponent()
            .appendingPathComponent("AndrewKeys", isDirectory: true)
        let legacyConfig = legacyDir.appendingPathComponent("config.json")
        guard fm.fileExists(atPath: legacyConfig.path) else { return }

        try? fm.copyItem(at: legacyConfig, to: configFile)

        // presets.tsv is regenerated by "Refresh from Lightroom", but copying
        // it means the preset pickers aren't empty on first open.
        let legacyPresets = legacyDir.appendingPathComponent("presets.tsv")
        let newPresets = dir.appendingPathComponent("presets.tsv")
        if fm.fileExists(atPath: legacyPresets.path), !fm.fileExists(atPath: newPresets.path) {
            try? fm.copyItem(at: legacyPresets, to: newPresets)
        }
    }

    func load() -> AppConfig {
        guard let data = try? Data(contentsOf: fileURL),
              let config = try? JSONDecoder().decode(AppConfig.self, from: data) else {
            return .default
        }
        return Self.normalized(config)
    }

    func save(_ config: AppConfig) {
        guard let data = try? JSONEncoder().encode(config) else { return }
        try? data.write(to: fileURL, options: .atomic)
    }

    /// Applied to every config coming from outside the running app -- the
    /// saved file at launch AND user-imported settings files -- so older
    /// exports/saves pick up migrations and newly added default bindings.
    static func normalized(_ config: AppConfig) -> AppConfig {
        var config = config

        // One-time migration: "Open Crop Tool" used to live in `sliders` as
        // a hack (amount-less, decrease-less). It's now its own ToolBinding
        // under `tools`, so drop the old slider entry if present.
        config.sliders.removeAll { $0.paramName == "OpenCropTool" }

        // Bring in any new default slider/tool (e.g. one added in a later
        // version of this app) that isn't already present, so existing
        // configs pick up new bindings without needing a manual reset.
        let existingParamNames = Set(config.sliders.map(\.paramName))
        for defaultSlider in AppConfig.default.sliders where !existingParamNames.contains(defaultSlider.paramName) {
            config.sliders.append(defaultSlider)
        }

        // Seed the non-raw white-balance step for configs saved before that
        // field existed (Temperature/Tint would otherwise use their large
        // raw step on JPG/TIFF). Only fills nils -- never overrides a value
        // the user set.
        let defaultRelative = Dictionary(
            uniqueKeysWithValues: AppConfig.default.sliders.compactMap { s in
                s.relativeAmount.map { (s.paramName, $0) }
            })
        for i in config.sliders.indices where config.sliders[i].relativeAmount == nil {
            if let seed = defaultRelative[config.sliders[i].paramName] {
                config.sliders[i].relativeAmount = seed
            }
        }

        let existingToolNames = Set(config.tools.map(\.toolName))
        for defaultTool in AppConfig.default.tools where !existingToolNames.contains(defaultTool.toolName) {
            config.tools.append(defaultTool)
        }

        return config
    }
}
